// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: dx/credits/v1/credits.proto

// Package dx.credits.v1 is the credit ledger's internal contract.
//
// It exists for one caller today: dx-user-go, which must provision a credit
// account before granting the `compute` realm role. A user holding compute with
// no ledger entry cannot compute, so the two operations belong together — and
// they live in different services because the ROLE is identity state and the
// LEDGER is not.
//
// The legacy Java platform kept both in one package
// (org.cdpg.dx.aaa.credit.handler.ComputeRoleHandler, with compute_role created
// in the same migration as the credit tables). The Go split separates them, and
// this contract is what puts them back in touch without merging the services.

package creditspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreditsService_EnsureAccount_FullMethodName = "/dx.credits.v1.CreditsService/EnsureAccount"
)

// CreditsServiceClient is the client API for CreditsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CreditsService serves ledger operations to other platform services.
//
// Internal only. External credit access goes through the gateway to
// dx-credits-go's REST surface; this exists so services do not have to hold a
// user's token to act on that user's behalf.
type CreditsServiceClient interface {
	// EnsureAccount creates the user's credit account if it does not exist.
	//
	// IDEMPOTENT BY CONTRACT, not by convention. The caller grants a role after
	// this returns, and a retry after a network timeout must not create a second
	// account or reset a balance. Callers may invoke it any number of times.
	EnsureAccount(ctx context.Context, in *EnsureAccountRequest, opts ...grpc.CallOption) (*EnsureAccountResponse, error)
}

type creditsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCreditsServiceClient(cc grpc.ClientConnInterface) CreditsServiceClient {
	return &creditsServiceClient{cc}
}

func (c *creditsServiceClient) EnsureAccount(ctx context.Context, in *EnsureAccountRequest, opts ...grpc.CallOption) (*EnsureAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureAccountResponse)
	err := c.cc.Invoke(ctx, CreditsService_EnsureAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreditsServiceServer is the server API for CreditsService service.
// All implementations must embed UnimplementedCreditsServiceServer
// for forward compatibility.
//
// CreditsService serves ledger operations to other platform services.
//
// Internal only. External credit access goes through the gateway to
// dx-credits-go's REST surface; this exists so services do not have to hold a
// user's token to act on that user's behalf.
type CreditsServiceServer interface {
	// EnsureAccount creates the user's credit account if it does not exist.
	//
	// IDEMPOTENT BY CONTRACT, not by convention. The caller grants a role after
	// this returns, and a retry after a network timeout must not create a second
	// account or reset a balance. Callers may invoke it any number of times.
	EnsureAccount(context.Context, *EnsureAccountRequest) (*EnsureAccountResponse, error)
	mustEmbedUnimplementedCreditsServiceServer()
}

// UnimplementedCreditsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreditsServiceServer struct{}

func (UnimplementedCreditsServiceServer) EnsureAccount(context.Context, *EnsureAccountRequest) (*EnsureAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureAccount not implemented")
}
func (UnimplementedCreditsServiceServer) mustEmbedUnimplementedCreditsServiceServer() {}
func (UnimplementedCreditsServiceServer) testEmbeddedByValue()                        {}

// UnsafeCreditsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreditsServiceServer will
// result in compilation errors.
type UnsafeCreditsServiceServer interface {
	mustEmbedUnimplementedCreditsServiceServer()
}

func RegisterCreditsServiceServer(s grpc.ServiceRegistrar, srv CreditsServiceServer) {
	// If the following call panics, it indicates UnimplementedCreditsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreditsService_ServiceDesc, srv)
}

func _CreditsService_EnsureAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditsServiceServer).EnsureAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditsService_EnsureAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditsServiceServer).EnsureAccount(ctx, req.(*EnsureAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreditsService_ServiceDesc is the grpc.ServiceDesc for CreditsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreditsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dx.credits.v1.CreditsService",
	HandlerType: (*CreditsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureAccount",
			Handler:    _CreditsService_EnsureAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dx/credits/v1/credits.proto",
}
