// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: dx/credits/v1/credits.proto

// Package dx.credits.v1 is the credit ledger's internal contract.
//
// It exists for one caller today: dx-user-go, which must provision a credit
// account before granting the `compute` realm role. A user holding compute with
// no ledger entry cannot compute, so the two operations belong together — and
// they live in different services because the ROLE is identity state and the
// LEDGER is not.
//
// The legacy Java platform kept both in one package
// (org.cdpg.dx.aaa.credit.handler.ComputeRoleHandler, with compute_role created
// in the same migration as the credit tables). The Go split separates them, and
// this contract is what puts them back in touch without merging the services.

package creditspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnsureAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user whose account is being provisioned.
	//
	// # Why a user id IS a body field here, unlike dx.catalogue.v1
	//
	// The catalogue contract deliberately keeps the subject out of the message
	// because there it identifies the CALLER, and a caller-supplied identity is
	// an unauthenticated claim (ADR-06).
	//
	// Here the field is a TARGET, not a claim: an administrator provisions an
	// account for somebody else. The caller's own authority still travels as
	// verified workload identity in metadata and is checked by the interceptor —
	// this field says who the work is FOR, and answers nothing about who asked.
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureAccountRequest) Reset() {
	*x = EnsureAccountRequest{}
	mi := &file_dx_credits_v1_credits_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureAccountRequest) ProtoMessage() {}

func (x *EnsureAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dx_credits_v1_credits_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureAccountRequest.ProtoReflect.Descriptor instead.
func (*EnsureAccountRequest) Descriptor() ([]byte, []int) {
	return file_dx_credits_v1_credits_proto_rawDescGZIP(), []int{0}
}

func (x *EnsureAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type EnsureAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when this call created the account, false when one already existed.
	//
	// Not an error either way — that is what idempotent means. It is returned so
	// the caller can log provisioning honestly rather than reporting a creation
	// that did not happen.
	Created bool `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	// The account's current balance, in the ledger's smallest unit.
	Balance       int64 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureAccountResponse) Reset() {
	*x = EnsureAccountResponse{}
	mi := &file_dx_credits_v1_credits_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureAccountResponse) ProtoMessage() {}

func (x *EnsureAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dx_credits_v1_credits_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureAccountResponse.ProtoReflect.Descriptor instead.
func (*EnsureAccountResponse) Descriptor() ([]byte, []int) {
	return file_dx_credits_v1_credits_proto_rawDescGZIP(), []int{1}
}

func (x *EnsureAccountResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *EnsureAccountResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_dx_credits_v1_credits_proto protoreflect.FileDescriptor

const file_dx_credits_v1_credits_proto_rawDesc = "" +
	"\n" +
	"\x1bdx/credits/v1/credits.proto\x12\rdx.credits.v1\"/\n" +
	"\x14EnsureAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"K\n" +
	"\x15EnsureAccountResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance2l\n" +
	"\x0eCreditsService\x12Z\n" +
	"\rEnsureAccount\x12#.dx.credits.v1.EnsureAccountRequest\x1a$.dx.credits.v1.EnsureAccountResponseB=Z;github.com/datakaveri/dx-common-go/grpc/creditspb;creditspbb\x06proto3"

var (
	file_dx_credits_v1_credits_proto_rawDescOnce sync.Once
	file_dx_credits_v1_credits_proto_rawDescData []byte
)

func file_dx_credits_v1_credits_proto_rawDescGZIP() []byte {
	file_dx_credits_v1_credits_proto_rawDescOnce.Do(func() {
		file_dx_credits_v1_credits_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dx_credits_v1_credits_proto_rawDesc), len(file_dx_credits_v1_credits_proto_rawDesc)))
	})
	return file_dx_credits_v1_credits_proto_rawDescData
}

var file_dx_credits_v1_credits_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dx_credits_v1_credits_proto_goTypes = []any{
	(*EnsureAccountRequest)(nil),  // 0: dx.credits.v1.EnsureAccountRequest
	(*EnsureAccountResponse)(nil), // 1: dx.credits.v1.EnsureAccountResponse
}
var file_dx_credits_v1_credits_proto_depIdxs = []int32{
	0, // 0: dx.credits.v1.CreditsService.EnsureAccount:input_type -> dx.credits.v1.EnsureAccountRequest
	1, // 1: dx.credits.v1.CreditsService.EnsureAccount:output_type -> dx.credits.v1.EnsureAccountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dx_credits_v1_credits_proto_init() }
func file_dx_credits_v1_credits_proto_init() {
	if File_dx_credits_v1_credits_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dx_credits_v1_credits_proto_rawDesc), len(file_dx_credits_v1_credits_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dx_credits_v1_credits_proto_goTypes,
		DependencyIndexes: file_dx_credits_v1_credits_proto_depIdxs,
		MessageInfos:      file_dx_credits_v1_credits_proto_msgTypes,
	}.Build()
	File_dx_credits_v1_credits_proto = out.File
	file_dx_credits_v1_credits_proto_goTypes = nil
	file_dx_credits_v1_credits_proto_depIdxs = nil
}
