// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: dx/catalogue/v1/catalogue.proto

// Package dx.catalogue.v1 is the catalogue's internal contract.
//
// This is the FIRST Go-owned gRPC contract in the platform. It deliberately
// does not extend org.cdpg.dx.auth.appid.v1 (grpc/appidpb), which is the JAVA
// control plane's AppIdVerificationService — that service bundles four
// unrelated jobs (VerifyAppId and ResolveDelegation are identity, CheckItemAccess
// is an authorization decision, GetItem is this) and is being removed.

package cataloguepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Item id (UUID).
	ItemId        string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_dx_catalogue_v1_catalogue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dx_catalogue_v1_catalogue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_dx_catalogue_v1_catalogue_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type GetItemResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False when no item exists for the id. Callers must check it: a zero-valued
	// Item is not the same as a missing one.
	Found         bool  `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Item          *Item `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_dx_catalogue_v1_catalogue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dx_catalogue_v1_catalogue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_dx_catalogue_v1_catalogue_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

// Item is the subset of a catalogue document other services consume. It is
// deliberately NOT the whole document: a contract that mirrors the storage
// shape makes every catalogue field an API commitment.
type Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Item type, e.g. DATABANK.
	Type        string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// The owning provider's user id (UUID).
	OwnerUserId      string `protobuf:"bytes,5,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	OrganizationId   string `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName string `protobuf:"bytes,7,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	AccessPolicy     string `protobuf:"bytes,8,opt,name=access_policy,json=accessPolicy,proto3" json:"access_policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_dx_catalogue_v1_catalogue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_dx_catalogue_v1_catalogue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_dx_catalogue_v1_catalogue_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Item) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Item) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *Item) GetAccessPolicy() string {
	if x != nil {
		return x.AccessPolicy
	}
	return ""
}

var File_dx_catalogue_v1_catalogue_proto protoreflect.FileDescriptor

const file_dx_catalogue_v1_catalogue_proto_rawDesc = "" +
	"\n" +
	"\x1fdx/catalogue/v1/catalogue.proto\x12\x0fdx.catalogue.v1\")\n" +
	"\x0eGetItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"R\n" +
	"\x0fGetItemResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12)\n" +
	"\x04item\x18\x02 \x01(\v2\x15.dx.catalogue.v1.ItemR\x04item\"\xff\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\"\n" +
	"\rowner_user_id\x18\x05 \x01(\tR\vownerUserId\x12'\n" +
	"\x0forganization_id\x18\x06 \x01(\tR\x0eorganizationId\x12+\n" +
	"\x11organization_name\x18\a \x01(\tR\x10organizationName\x12#\n" +
	"\raccess_policy\x18\b \x01(\tR\faccessPolicy2`\n" +
	"\x10CatalogueService\x12L\n" +
	"\aGetItem\x12\x1f.dx.catalogue.v1.GetItemRequest\x1a .dx.catalogue.v1.GetItemResponseBAZ?github.com/datakaveri/dx-common-go/grpc/cataloguepb;cataloguepbb\x06proto3"

var (
	file_dx_catalogue_v1_catalogue_proto_rawDescOnce sync.Once
	file_dx_catalogue_v1_catalogue_proto_rawDescData []byte
)

func file_dx_catalogue_v1_catalogue_proto_rawDescGZIP() []byte {
	file_dx_catalogue_v1_catalogue_proto_rawDescOnce.Do(func() {
		file_dx_catalogue_v1_catalogue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dx_catalogue_v1_catalogue_proto_rawDesc), len(file_dx_catalogue_v1_catalogue_proto_rawDesc)))
	})
	return file_dx_catalogue_v1_catalogue_proto_rawDescData
}

var file_dx_catalogue_v1_catalogue_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dx_catalogue_v1_catalogue_proto_goTypes = []any{
	(*GetItemRequest)(nil),  // 0: dx.catalogue.v1.GetItemRequest
	(*GetItemResponse)(nil), // 1: dx.catalogue.v1.GetItemResponse
	(*Item)(nil),            // 2: dx.catalogue.v1.Item
}
var file_dx_catalogue_v1_catalogue_proto_depIdxs = []int32{
	2, // 0: dx.catalogue.v1.GetItemResponse.item:type_name -> dx.catalogue.v1.Item
	0, // 1: dx.catalogue.v1.CatalogueService.GetItem:input_type -> dx.catalogue.v1.GetItemRequest
	1, // 2: dx.catalogue.v1.CatalogueService.GetItem:output_type -> dx.catalogue.v1.GetItemResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dx_catalogue_v1_catalogue_proto_init() }
func file_dx_catalogue_v1_catalogue_proto_init() {
	if File_dx_catalogue_v1_catalogue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dx_catalogue_v1_catalogue_proto_rawDesc), len(file_dx_catalogue_v1_catalogue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dx_catalogue_v1_catalogue_proto_goTypes,
		DependencyIndexes: file_dx_catalogue_v1_catalogue_proto_depIdxs,
		MessageInfos:      file_dx_catalogue_v1_catalogue_proto_msgTypes,
	}.Build()
	File_dx_catalogue_v1_catalogue_proto = out.File
	file_dx_catalogue_v1_catalogue_proto_goTypes = nil
	file_dx_catalogue_v1_catalogue_proto_depIdxs = nil
}
