// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: appid_verification.proto

package appidpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── VerifyAppId ────────────────────────────────────────────────────────────
type VerifyAppIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`             // UUID string — safe to log
	AppSecret     string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"` // plaintext — NEVER log
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAppIdRequest) Reset() {
	*x = VerifyAppIdRequest{}
	mi := &file_appid_verification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAppIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAppIdRequest) ProtoMessage() {}

func (x *VerifyAppIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appid_verification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAppIdRequest.ProtoReflect.Descriptor instead.
func (*VerifyAppIdRequest) Descriptor() ([]byte, []int) {
	return file_appid_verification_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyAppIdRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *VerifyAppIdRequest) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

type VerifyAppIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // empty on success; INVALID_CREDENTIALS | REVOKED | EXPIRED
	Principal     *AppIdPrincipalProto   `protobuf:"bytes,3,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAppIdResponse) Reset() {
	*x = VerifyAppIdResponse{}
	mi := &file_appid_verification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAppIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAppIdResponse) ProtoMessage() {}

func (x *VerifyAppIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appid_verification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAppIdResponse.ProtoReflect.Descriptor instead.
func (*VerifyAppIdResponse) Descriptor() ([]byte, []int) {
	return file_appid_verification_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyAppIdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyAppIdResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *VerifyAppIdResponse) GetPrincipal() *AppIdPrincipalProto {
	if x != nil {
		return x.Principal
	}
	return nil
}

// Identity-only principal — no item metadata (that comes from CheckItemAccess).
type AppIdPrincipalProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                            // user_id from app_credentials
	Roles          []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`                                            // e.g. ["consumer"]
	Scopes         []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`                                          // e.g. ["data_access"]
	ExpiresAtEpoch int64                  `protobuf:"varint,6,opt,name=expires_at_epoch,json=expiresAtEpoch,proto3" json:"expires_at_epoch,omitempty"` // 0 = no expiry; field 5 reserved
	OrganisationId string                 `protobuf:"bytes,7,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"`    // owner's organisation UUID from Keycloak
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppIdPrincipalProto) Reset() {
	*x = AppIdPrincipalProto{}
	mi := &file_appid_verification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppIdPrincipalProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppIdPrincipalProto) ProtoMessage() {}

func (x *AppIdPrincipalProto) ProtoReflect() protoreflect.Message {
	mi := &file_appid_verification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppIdPrincipalProto.ProtoReflect.Descriptor instead.
func (*AppIdPrincipalProto) Descriptor() ([]byte, []int) {
	return file_appid_verification_proto_rawDescGZIP(), []int{2}
}

func (x *AppIdPrincipalProto) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppIdPrincipalProto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AppIdPrincipalProto) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AppIdPrincipalProto) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *AppIdPrincipalProto) GetExpiresAtEpoch() int64 {
	if x != nil {
		return x.ExpiresAtEpoch
	}
	return 0
}

func (x *AppIdPrincipalProto) GetOrganisationId() string {
	if x != nil {
		return x.OrganisationId
	}
	return ""
}

// ── CheckItemAccess ────────────────────────────────────────────────────────
type CheckItemAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // userId from VerifyAppId response — no extra DB lookup needed
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Did           string                 `protobuf:"bytes,3,opt,name=did,proto3" json:"did,omitempty"` // optional; empty = direct access, non-empty = delegation check (userId → did)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckItemAccessRequest) Reset() {
	*x = CheckItemAccessRequest{}
	mi := &file_appid_verification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckItemAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckItemAccessRequest) ProtoMessage() {}

func (x *CheckItemAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appid_verification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckItemAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckItemAccessRequest) Descriptor() ([]byte, []int) {
	return file_appid_verification_proto_rawDescGZIP(), []int{3}
}

func (x *CheckItemAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckItemAccessRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CheckItemAccessRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type CheckItemAccessResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode          string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // NO_ACCESS | NOT_FOUND | INTERNAL_ERROR
	Iid                string                 `protobuf:"bytes,3,opt,name=iid,proto3" json:"iid,omitempty"`
	AccessPolicy       string                 `protobuf:"bytes,4,opt,name=access_policy,json=accessPolicy,proto3" json:"access_policy,omitempty"`
	ResourceServerJson string                 `protobuf:"bytes,5,opt,name=resource_server_json,json=resourceServerJson,proto3" json:"resource_server_json,omitempty"` // JSON-encoded resourceServer array
	PoliciesJson       string                 `protobuf:"bytes,6,opt,name=policies_json,json=policiesJson,proto3" json:"policies_json,omitempty"`                     // JSON-encoded policies array
	HasOwnerAccess     bool                   `protobuf:"varint,7,opt,name=has_owner_access,json=hasOwnerAccess,proto3" json:"has_owner_access,omitempty"`            // caller is the item owner — full access, no policy needed
	HasAdminAccess     bool                   `protobuf:"varint,8,opt,name=has_admin_access,json=hasAdminAccess,proto3" json:"has_admin_access,omitempty"`            // caller is an admin — full access, no policy needed
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CheckItemAccessResponse) Reset() {
	*x = CheckItemAccessResponse{}
	mi := &file_appid_verification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckItemAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckItemAccessResponse) ProtoMessage() {}

func (x *CheckItemAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appid_verification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckItemAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckItemAccessResponse) Descriptor() ([]byte, []int) {
	return file_appid_verification_proto_rawDescGZIP(), []int{4}
}

func (x *CheckItemAccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckItemAccessResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CheckItemAccessResponse) GetIid() string {
	if x != nil {
		return x.Iid
	}
	return ""
}

func (x *CheckItemAccessResponse) GetAccessPolicy() string {
	if x != nil {
		return x.AccessPolicy
	}
	return ""
}

func (x *CheckItemAccessResponse) GetResourceServerJson() string {
	if x != nil {
		return x.ResourceServerJson
	}
	return ""
}

func (x *CheckItemAccessResponse) GetPoliciesJson() string {
	if x != nil {
		return x.PoliciesJson
	}
	return ""
}

func (x *CheckItemAccessResponse) GetHasOwnerAccess() bool {
	if x != nil {
		return x.HasOwnerAccess
	}
	return false
}

func (x *CheckItemAccessResponse) GetHasAdminAccess() bool {
	if x != nil {
		return x.HasAdminAccess
	}
	return false
}

// ── ResolveDelegation ──────────────────────────────────────────────────────
type ResolveDelegationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelegatorSub  string                 `protobuf:"bytes,1,opt,name=delegator_sub,json=delegatorSub,proto3" json:"delegator_sub,omitempty"`
	DelegateeSub  string                 `protobuf:"bytes,2,opt,name=delegatee_sub,json=delegateeSub,proto3" json:"delegatee_sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDelegationRequest) Reset() {
	*x = ResolveDelegationRequest{}
	mi := &file_appid_verification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDelegationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDelegationRequest) ProtoMessage() {}

func (x *ResolveDelegationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appid_verification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDelegationRequest.ProtoReflect.Descriptor instead.
func (*ResolveDelegationRequest) Descriptor() ([]byte, []int) {
	return file_appid_verification_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveDelegationRequest) GetDelegatorSub() string {
	if x != nil {
		return x.DelegatorSub
	}
	return ""
}

func (x *ResolveDelegationRequest) GetDelegateeSub() string {
	if x != nil {
		return x.DelegateeSub
	}
	return ""
}

type ResolveDelegationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode         string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // NO_ACTIVE_DELEGATION | EXPIRED | DELEGATOR_INACTIVE | INTERNAL_ERROR
	Sub               string                 `protobuf:"bytes,3,opt,name=sub,proto3" json:"sub,omitempty"`                              // delegator's sub (UUID)
	OrganisationId    string                 `protobuf:"bytes,4,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"`
	OrganisationName  string                 `protobuf:"bytes,5,opt,name=organisation_name,json=organisationName,proto3" json:"organisation_name,omitempty"`
	Roles             []string               `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	Scopes            []string               `protobuf:"bytes,7,rep,name=scopes,proto3" json:"scopes,omitempty"`
	EmailVerified     bool                   `protobuf:"varint,8,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	KycVerified       bool                   `protobuf:"varint,9,opt,name=kyc_verified,json=kycVerified,proto3" json:"kyc_verified,omitempty"`
	Name              string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	PreferredUsername string                 `protobuf:"bytes,11,opt,name=preferred_username,json=preferredUsername,proto3" json:"preferred_username,omitempty"`
	GivenName         string                 `protobuf:"bytes,12,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName        string                 `protobuf:"bytes,13,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Email             string                 `protobuf:"bytes,14,opt,name=email,proto3" json:"email,omitempty"`
	AccountEnabled    bool                   `protobuf:"varint,15,opt,name=account_enabled,json=accountEnabled,proto3" json:"account_enabled,omitempty"`
	DelegateeSub      string                 `protobuf:"bytes,16,opt,name=delegatee_sub,json=delegateeSub,proto3" json:"delegatee_sub,omitempty"` // echoed back for audit
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveDelegationResponse) Reset() {
	*x = ResolveDelegationResponse{}
	mi := &file_appid_verification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDelegationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDelegationResponse) ProtoMessage() {}

func (x *ResolveDelegationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appid_verification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDelegationResponse.ProtoReflect.Descriptor instead.
func (*ResolveDelegationResponse) Descriptor() ([]byte, []int) {
	return file_appid_verification_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveDelegationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResolveDelegationResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ResolveDelegationResponse) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *ResolveDelegationResponse) GetOrganisationId() string {
	if x != nil {
		return x.OrganisationId
	}
	return ""
}

func (x *ResolveDelegationResponse) GetOrganisationName() string {
	if x != nil {
		return x.OrganisationName
	}
	return ""
}

func (x *ResolveDelegationResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ResolveDelegationResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ResolveDelegationResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *ResolveDelegationResponse) GetKycVerified() bool {
	if x != nil {
		return x.KycVerified
	}
	return false
}

func (x *ResolveDelegationResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolveDelegationResponse) GetPreferredUsername() string {
	if x != nil {
		return x.PreferredUsername
	}
	return ""
}

func (x *ResolveDelegationResponse) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *ResolveDelegationResponse) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *ResolveDelegationResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResolveDelegationResponse) GetAccountEnabled() bool {
	if x != nil {
		return x.AccountEnabled
	}
	return false
}

func (x *ResolveDelegationResponse) GetDelegateeSub() string {
	if x != nil {
		return x.DelegateeSub
	}
	return ""
}

// ── GetItem ────────────────────────────────────────────────────────────────
// Catalogue item lookup for external PAPs (e.g. dx-acl-go). Replaces the
// Vert.x ItemService proxy the in-process Java ACL uses.
type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // catalogue item UUID
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // caller sub, for audit; may be empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_appid_verification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appid_verification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_appid_verification_proto_rawDescGZIP(), []int{7}
}

func (x *GetItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GetItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetItemResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Found              bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	ErrorCode          string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // NOT_FOUND | INTERNAL_ERROR; empty on success
	ItemId             string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemType           string                 `protobuf:"bytes,4,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`                     // DATABANK | AIMODEL | APPS
	ProviderUserId     string                 `protobuf:"bytes,5,opt,name=provider_user_id,json=providerUserId,proto3" json:"provider_user_id,omitempty"` // owner of the item
	OrganizationId     string                 `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`   // may be empty for independent providers
	OrganizationName   string                 `protobuf:"bytes,7,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	ResourceServerJson string                 `protobuf:"bytes,8,opt,name=resource_server_json,json=resourceServerJson,proto3" json:"resource_server_json,omitempty"` // JSON-encoded resourceServer array (incl. accessTypes)
	ApdUrl             string                 `protobuf:"bytes,9,opt,name=apd_url,json=apdUrl,proto3" json:"apd_url,omitempty"`                                       // APD that governs this item
	AssetName          string                 `protobuf:"bytes,10,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	ShortDescription   string                 `protobuf:"bytes,11,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_appid_verification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appid_verification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_appid_verification_proto_rawDescGZIP(), []int{8}
}

func (x *GetItemResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetItemResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetItemResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GetItemResponse) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *GetItemResponse) GetProviderUserId() string {
	if x != nil {
		return x.ProviderUserId
	}
	return ""
}

func (x *GetItemResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetItemResponse) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *GetItemResponse) GetResourceServerJson() string {
	if x != nil {
		return x.ResourceServerJson
	}
	return ""
}

func (x *GetItemResponse) GetApdUrl() string {
	if x != nil {
		return x.ApdUrl
	}
	return ""
}

func (x *GetItemResponse) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *GetItemResponse) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

var File_appid_verification_proto protoreflect.FileDescriptor

const file_appid_verification_proto_rawDesc = "" +
	"\n" +
	"\x18appid_verification.proto\x12\x19org.cdpg.dx.auth.appid.v1\"J\n" +
	"\x12VerifyAppIdRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tR\tappSecret\"\x9c\x01\n" +
	"\x13VerifyAppIdResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12L\n" +
	"\tprincipal\x18\x03 \x01(\v2..org.cdpg.dx.auth.appid.v1.AppIdPrincipalProtoR\tprincipal\"\xc6\x01\n" +
	"\x13AppIdPrincipalProto\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12(\n" +
	"\x10expires_at_epoch\x18\x06 \x01(\x03R\x0eexpiresAtEpoch\x12'\n" +
	"\x0forganisation_id\x18\a \x01(\tR\x0eorganisationId\"`\n" +
	"\x16CheckItemAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x10\n" +
	"\x03did\x18\x03 \x01(\tR\x03did\"\xb4\x02\n" +
	"\x17CheckItemAccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x10\n" +
	"\x03iid\x18\x03 \x01(\tR\x03iid\x12#\n" +
	"\raccess_policy\x18\x04 \x01(\tR\faccessPolicy\x120\n" +
	"\x14resource_server_json\x18\x05 \x01(\tR\x12resourceServerJson\x12#\n" +
	"\rpolicies_json\x18\x06 \x01(\tR\fpoliciesJson\x12(\n" +
	"\x10has_owner_access\x18\a \x01(\bR\x0ehasOwnerAccess\x12(\n" +
	"\x10has_admin_access\x18\b \x01(\bR\x0ehasAdminAccess\"d\n" +
	"\x18ResolveDelegationRequest\x12#\n" +
	"\rdelegator_sub\x18\x01 \x01(\tR\fdelegatorSub\x12#\n" +
	"\rdelegatee_sub\x18\x02 \x01(\tR\fdelegateeSub\"\x9b\x04\n" +
	"\x19ResolveDelegationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x10\n" +
	"\x03sub\x18\x03 \x01(\tR\x03sub\x12'\n" +
	"\x0forganisation_id\x18\x04 \x01(\tR\x0eorganisationId\x12+\n" +
	"\x11organisation_name\x18\x05 \x01(\tR\x10organisationName\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles\x12\x16\n" +
	"\x06scopes\x18\a \x03(\tR\x06scopes\x12%\n" +
	"\x0eemail_verified\x18\b \x01(\bR\remailVerified\x12!\n" +
	"\fkyc_verified\x18\t \x01(\bR\vkycVerified\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12-\n" +
	"\x12preferred_username\x18\v \x01(\tR\x11preferredUsername\x12\x1d\n" +
	"\n" +
	"given_name\x18\f \x01(\tR\tgivenName\x12\x1f\n" +
	"\vfamily_name\x18\r \x01(\tR\n" +
	"familyName\x12\x14\n" +
	"\x05email\x18\x0e \x01(\tR\x05email\x12'\n" +
	"\x0faccount_enabled\x18\x0f \x01(\bR\x0eaccountEnabled\x12#\n" +
	"\rdelegatee_sub\x18\x10 \x01(\tR\fdelegateeSub\"B\n" +
	"\x0eGetItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x93\x03\n" +
	"\x0fGetItemResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_type\x18\x04 \x01(\tR\bitemType\x12(\n" +
	"\x10provider_user_id\x18\x05 \x01(\tR\x0eproviderUserId\x12'\n" +
	"\x0forganization_id\x18\x06 \x01(\tR\x0eorganizationId\x12+\n" +
	"\x11organization_name\x18\a \x01(\tR\x10organizationName\x120\n" +
	"\x14resource_server_json\x18\b \x01(\tR\x12resourceServerJson\x12\x17\n" +
	"\aapd_url\x18\t \x01(\tR\x06apdUrl\x12\x1d\n" +
	"\n" +
	"asset_name\x18\n" +
	" \x01(\tR\tassetName\x12+\n" +
	"\x11short_description\x18\v \x01(\tR\x10shortDescription2\xe4\x03\n" +
	"\x18AppIdVerificationService\x12l\n" +
	"\vVerifyAppId\x12-.org.cdpg.dx.auth.appid.v1.VerifyAppIdRequest\x1a..org.cdpg.dx.auth.appid.v1.VerifyAppIdResponse\x12x\n" +
	"\x0fCheckItemAccess\x121.org.cdpg.dx.auth.appid.v1.CheckItemAccessRequest\x1a2.org.cdpg.dx.auth.appid.v1.CheckItemAccessResponse\x12~\n" +
	"\x11ResolveDelegation\x123.org.cdpg.dx.auth.appid.v1.ResolveDelegationRequest\x1a4.org.cdpg.dx.auth.appid.v1.ResolveDelegationResponse\x12`\n" +
	"\aGetItem\x12).org.cdpg.dx.auth.appid.v1.GetItemRequest\x1a*.org.cdpg.dx.auth.appid.v1.GetItemResponseBf\n" +
	"\x19org.cdpg.dx.auth.appid.v1B\x16AppIdVerificationProtoP\x01Z/github.com/datakaveri/dx-common-go/grpc/appidpbb\x06proto3"

var (
	file_appid_verification_proto_rawDescOnce sync.Once
	file_appid_verification_proto_rawDescData []byte
)

func file_appid_verification_proto_rawDescGZIP() []byte {
	file_appid_verification_proto_rawDescOnce.Do(func() {
		file_appid_verification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appid_verification_proto_rawDesc), len(file_appid_verification_proto_rawDesc)))
	})
	return file_appid_verification_proto_rawDescData
}

var file_appid_verification_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_appid_verification_proto_goTypes = []any{
	(*VerifyAppIdRequest)(nil),        // 0: org.cdpg.dx.auth.appid.v1.VerifyAppIdRequest
	(*VerifyAppIdResponse)(nil),       // 1: org.cdpg.dx.auth.appid.v1.VerifyAppIdResponse
	(*AppIdPrincipalProto)(nil),       // 2: org.cdpg.dx.auth.appid.v1.AppIdPrincipalProto
	(*CheckItemAccessRequest)(nil),    // 3: org.cdpg.dx.auth.appid.v1.CheckItemAccessRequest
	(*CheckItemAccessResponse)(nil),   // 4: org.cdpg.dx.auth.appid.v1.CheckItemAccessResponse
	(*ResolveDelegationRequest)(nil),  // 5: org.cdpg.dx.auth.appid.v1.ResolveDelegationRequest
	(*ResolveDelegationResponse)(nil), // 6: org.cdpg.dx.auth.appid.v1.ResolveDelegationResponse
	(*GetItemRequest)(nil),            // 7: org.cdpg.dx.auth.appid.v1.GetItemRequest
	(*GetItemResponse)(nil),           // 8: org.cdpg.dx.auth.appid.v1.GetItemResponse
}
var file_appid_verification_proto_depIdxs = []int32{
	2, // 0: org.cdpg.dx.auth.appid.v1.VerifyAppIdResponse.principal:type_name -> org.cdpg.dx.auth.appid.v1.AppIdPrincipalProto
	0, // 1: org.cdpg.dx.auth.appid.v1.AppIdVerificationService.VerifyAppId:input_type -> org.cdpg.dx.auth.appid.v1.VerifyAppIdRequest
	3, // 2: org.cdpg.dx.auth.appid.v1.AppIdVerificationService.CheckItemAccess:input_type -> org.cdpg.dx.auth.appid.v1.CheckItemAccessRequest
	5, // 3: org.cdpg.dx.auth.appid.v1.AppIdVerificationService.ResolveDelegation:input_type -> org.cdpg.dx.auth.appid.v1.ResolveDelegationRequest
	7, // 4: org.cdpg.dx.auth.appid.v1.AppIdVerificationService.GetItem:input_type -> org.cdpg.dx.auth.appid.v1.GetItemRequest
	1, // 5: org.cdpg.dx.auth.appid.v1.AppIdVerificationService.VerifyAppId:output_type -> org.cdpg.dx.auth.appid.v1.VerifyAppIdResponse
	4, // 6: org.cdpg.dx.auth.appid.v1.AppIdVerificationService.CheckItemAccess:output_type -> org.cdpg.dx.auth.appid.v1.CheckItemAccessResponse
	6, // 7: org.cdpg.dx.auth.appid.v1.AppIdVerificationService.ResolveDelegation:output_type -> org.cdpg.dx.auth.appid.v1.ResolveDelegationResponse
	8, // 8: org.cdpg.dx.auth.appid.v1.AppIdVerificationService.GetItem:output_type -> org.cdpg.dx.auth.appid.v1.GetItemResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_appid_verification_proto_init() }
func file_appid_verification_proto_init() {
	if File_appid_verification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appid_verification_proto_rawDesc), len(file_appid_verification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appid_verification_proto_goTypes,
		DependencyIndexes: file_appid_verification_proto_depIdxs,
		MessageInfos:      file_appid_verification_proto_msgTypes,
	}.Build()
	File_appid_verification_proto = out.File
	file_appid_verification_proto_goTypes = nil
	file_appid_verification_proto_depIdxs = nil
}
