// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: dx/authz/v1/authz.proto

// Package dx.authz.v1 is the internal gRPC mirror of the AuthZEN Access
// Evaluation contract (ADR-14 / §4.6).
//
// The JSON model at POST /access/v1/evaluation is CANONICAL. This exists only so
// hot-path internal callers (a PEP evaluating against the PDP many times per
// request) can avoid JSON on the wire. A round-trip equivalence test pins the
// two representations together, so the mirror can never silently drift from the
// contract it mirrors.
//
// Free-form members (`properties`) are google.protobuf.Struct — faithful to
// arbitrary JSON. Response entitlements/obligations are NOT remirrored: they
// travel to a data plane inside the signed attestation (JWS), which the data
// plane verifies itself (invariant I-8), never as fields a caller reads here.

package authzpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *Subject               `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Action        *Action                `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      *Resource              `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Context       *RequestContext        `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationRequest) Reset() {
	*x = EvaluationRequest{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationRequest) ProtoMessage() {}

func (x *EvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationRequest.ProtoReflect.Descriptor instead.
func (*EvaluationRequest) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluationRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *EvaluationRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *EvaluationRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *EvaluationRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type Subject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{1}
}

func (x *Subject) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Subject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subject) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{2}
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{3}
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type RequestContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Dx            *DXRequestContext      `protobuf:"bytes,2,opt,name=dx,proto3" json:"dx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{4}
}

func (x *RequestContext) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *RequestContext) GetDx() *DXRequestContext {
	if x != nil {
		return x.Dx
	}
	return nil
}

type DXRequestContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Operation     *OperationRef          `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Actor         *Actor                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	Pep           *PEPInfo               `protobuf:"bytes,4,opt,name=pep,proto3" json:"pep,omitempty"`
	Purpose       string                 `protobuf:"bytes,5,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Request       *RequestFacts          `protobuf:"bytes,6,opt,name=request,proto3" json:"request,omitempty"`
	Approval      *ApprovalRef           `protobuf:"bytes,7,opt,name=approval,proto3" json:"approval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DXRequestContext) Reset() {
	*x = DXRequestContext{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DXRequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DXRequestContext) ProtoMessage() {}

func (x *DXRequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DXRequestContext.ProtoReflect.Descriptor instead.
func (*DXRequestContext) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{5}
}

func (x *DXRequestContext) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *DXRequestContext) GetOperation() *OperationRef {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *DXRequestContext) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *DXRequestContext) GetPep() *PEPInfo {
	if x != nil {
		return x.Pep
	}
	return nil
}

func (x *DXRequestContext) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *DXRequestContext) GetRequest() *RequestFacts {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *DXRequestContext) GetApproval() *ApprovalRef {
	if x != nil {
		return x.Approval
	}
	return nil
}

type OperationRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Service        string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ManifestDigest string                 `protobuf:"bytes,3,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OperationRef) Reset() {
	*x = OperationRef{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRef) ProtoMessage() {}

func (x *OperationRef) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRef.ProtoReflect.Descriptor instead.
func (*OperationRef) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{6}
}

func (x *OperationRef) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *OperationRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OperationRef) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DelegationId  string                 `protobuf:"bytes,3,opt,name=delegation_id,json=delegationId,proto3" json:"delegation_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Chain         []string               `protobuf:"bytes,5,rep,name=chain,proto3" json:"chain,omitempty"`
	TransactionId string                 `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,7,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{7}
}

func (x *Actor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Actor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Actor) GetDelegationId() string {
	if x != nil {
		return x.DelegationId
	}
	return ""
}

func (x *Actor) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Actor) GetChain() []string {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *Actor) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Actor) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type PEPInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PEPInfo) Reset() {
	*x = PEPInfo{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PEPInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PEPInfo) ProtoMessage() {}

func (x *PEPInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PEPInfo.ProtoReflect.Descriptor instead.
func (*PEPInfo) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{8}
}

func (x *PEPInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PEPInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RequestFacts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	DeliveryMode  string                 `protobuf:"bytes,2,opt,name=delivery_mode,json=deliveryMode,proto3" json:"delivery_mode,omitempty"`
	TermsHash     string                 `protobuf:"bytes,3,opt,name=terms_hash,json=termsHash,proto3" json:"terms_hash,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Payee         string                 `protobuf:"bytes,6,opt,name=payee,proto3" json:"payee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFacts) Reset() {
	*x = RequestFacts{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFacts) ProtoMessage() {}

func (x *RequestFacts) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFacts.ProtoReflect.Descriptor instead.
func (*RequestFacts) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{9}
}

func (x *RequestFacts) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *RequestFacts) GetDeliveryMode() string {
	if x != nil {
		return x.DeliveryMode
	}
	return ""
}

func (x *RequestFacts) GetTermsHash() string {
	if x != nil {
		return x.TermsHash
	}
	return ""
}

func (x *RequestFacts) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *RequestFacts) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RequestFacts) GetPayee() string {
	if x != nil {
		return x.Payee
	}
	return ""
}

type ApprovalRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApprovedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	ApprovedUntil *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=approved_until,json=approvedUntil,proto3" json:"approved_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRef) Reset() {
	*x = ApprovalRef{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRef) ProtoMessage() {}

func (x *ApprovalRef) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRef.ProtoReflect.Descriptor instead.
func (*ApprovalRef) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{10}
}

func (x *ApprovalRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApprovalRef) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

func (x *ApprovalRef) GetApprovedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedUntil
	}
	return nil
}

type EvaluationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      bool                   `protobuf:"varint,1,opt,name=decision,proto3" json:"decision,omitempty"`
	Context       *DecisionContext       `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationResponse) Reset() {
	*x = EvaluationResponse{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationResponse) ProtoMessage() {}

func (x *EvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationResponse.ProtoReflect.Descriptor instead.
func (*EvaluationResponse) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{11}
}

func (x *EvaluationResponse) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

func (x *EvaluationResponse) GetContext() *DecisionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type DecisionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReasonUser    string                 `protobuf:"bytes,1,opt,name=reason_user,json=reasonUser,proto3" json:"reason_user,omitempty"`
	Dx            *DXDecisionContext     `protobuf:"bytes,2,opt,name=dx,proto3" json:"dx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionContext) Reset() {
	*x = DecisionContext{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionContext) ProtoMessage() {}

func (x *DecisionContext) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionContext.ProtoReflect.Descriptor instead.
func (*DecisionContext) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{12}
}

func (x *DecisionContext) GetReasonUser() string {
	if x != nil {
		return x.ReasonUser
	}
	return ""
}

func (x *DecisionContext) GetDx() *DXDecisionContext {
	if x != nil {
		return x.Dx
	}
	return nil
}

type DXDecisionContext struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Profile          string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	EvaluationId     string                 `protobuf:"bytes,2,opt,name=evaluation_id,json=evaluationId,proto3" json:"evaluation_id,omitempty"`
	ReasonCode       string                 `protobuf:"bytes,3,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	Complete         bool                   `protobuf:"varint,4,opt,name=complete,proto3" json:"complete,omitempty"`
	EvaluatedProfile string                 `protobuf:"bytes,5,opt,name=evaluated_profile,json=evaluatedProfile,proto3" json:"evaluated_profile,omitempty"`
	ValidUntil       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	Evidence         *Evidence              `protobuf:"bytes,7,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Attestation      string                 `protobuf:"bytes,8,opt,name=attestation,proto3" json:"attestation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DXDecisionContext) Reset() {
	*x = DXDecisionContext{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DXDecisionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DXDecisionContext) ProtoMessage() {}

func (x *DXDecisionContext) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DXDecisionContext.ProtoReflect.Descriptor instead.
func (*DXDecisionContext) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{13}
}

func (x *DXDecisionContext) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *DXDecisionContext) GetEvaluationId() string {
	if x != nil {
		return x.EvaluationId
	}
	return ""
}

func (x *DXDecisionContext) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *DXDecisionContext) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *DXDecisionContext) GetEvaluatedProfile() string {
	if x != nil {
		return x.EvaluatedProfile
	}
	return ""
}

func (x *DXDecisionContext) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *DXDecisionContext) GetEvidence() *Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *DXDecisionContext) GetAttestation() string {
	if x != nil {
		return x.Attestation
	}
	return ""
}

type Evidence struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ManifestDigest          string                 `protobuf:"bytes,1,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	FgaModelId              string                 `protobuf:"bytes,2,opt,name=fga_model_id,json=fgaModelId,proto3" json:"fga_model_id,omitempty"`
	GrantProjectionRevision string                 `protobuf:"bytes,3,opt,name=grant_projection_revision,json=grantProjectionRevision,proto3" json:"grant_projection_revision,omitempty"`
	ConditionSchemaVersion  int32                  `protobuf:"varint,4,opt,name=condition_schema_version,json=conditionSchemaVersion,proto3" json:"condition_schema_version,omitempty"`
	MappingDigest           string                 `protobuf:"bytes,5,opt,name=mapping_digest,json=mappingDigest,proto3" json:"mapping_digest,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{14}
}

func (x *Evidence) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

func (x *Evidence) GetFgaModelId() string {
	if x != nil {
		return x.FgaModelId
	}
	return ""
}

func (x *Evidence) GetGrantProjectionRevision() string {
	if x != nil {
		return x.GrantProjectionRevision
	}
	return ""
}

func (x *Evidence) GetConditionSchemaVersion() int32 {
	if x != nil {
		return x.ConditionSchemaVersion
	}
	return 0
}

func (x *Evidence) GetMappingDigest() string {
	if x != nil {
		return x.MappingDigest
	}
	return ""
}

type EvaluationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evaluations   []*EvaluationRequest   `protobuf:"bytes,1,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationsRequest) Reset() {
	*x = EvaluationsRequest{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationsRequest) ProtoMessage() {}

func (x *EvaluationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationsRequest.ProtoReflect.Descriptor instead.
func (*EvaluationsRequest) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{15}
}

func (x *EvaluationsRequest) GetEvaluations() []*EvaluationRequest {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

type EvaluationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evaluations   []*EvaluationResponse  `protobuf:"bytes,1,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationsResponse) Reset() {
	*x = EvaluationsResponse{}
	mi := &file_dx_authz_v1_authz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationsResponse) ProtoMessage() {}

func (x *EvaluationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dx_authz_v1_authz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationsResponse.ProtoReflect.Descriptor instead.
func (*EvaluationsResponse) Descriptor() ([]byte, []int) {
	return file_dx_authz_v1_authz_proto_rawDescGZIP(), []int{16}
}

func (x *EvaluationsResponse) GetEvaluations() []*EvaluationResponse {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

var File_dx_authz_v1_authz_proto protoreflect.FileDescriptor

const file_dx_authz_v1_authz_proto_rawDesc = "" +
	"\n" +
	"\x17dx/authz/v1/authz.proto\x12\vdx.authz.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x01\n" +
	"\x11EvaluationRequest\x12.\n" +
	"\asubject\x18\x01 \x01(\v2\x14.dx.authz.v1.SubjectR\asubject\x12+\n" +
	"\x06action\x18\x02 \x01(\v2\x13.dx.authz.v1.ActionR\x06action\x121\n" +
	"\bresource\x18\x03 \x01(\v2\x15.dx.authz.v1.ResourceR\bresource\x125\n" +
	"\acontext\x18\x04 \x01(\v2\x1b.dx.authz.v1.RequestContextR\acontext\"f\n" +
	"\aSubject\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x127\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"U\n" +
	"\x06Action\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\n" +
	"properties\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"g\n" +
	"\bResource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x127\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"U\n" +
	"\x0eRequestContext\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12-\n" +
	"\x02dx\x18\x02 \x01(\v2\x1d.dx.authz.v1.DXRequestContextR\x02dx\"\xbc\x02\n" +
	"\x10DXRequestContext\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x127\n" +
	"\toperation\x18\x02 \x01(\v2\x19.dx.authz.v1.OperationRefR\toperation\x12(\n" +
	"\x05actor\x18\x03 \x01(\v2\x12.dx.authz.v1.ActorR\x05actor\x12&\n" +
	"\x03pep\x18\x04 \x01(\v2\x14.dx.authz.v1.PEPInfoR\x03pep\x12\x18\n" +
	"\apurpose\x18\x05 \x01(\tR\apurpose\x123\n" +
	"\arequest\x18\x06 \x01(\v2\x19.dx.authz.v1.RequestFactsR\arequest\x124\n" +
	"\bapproval\x18\a \x01(\v2\x18.dx.authz.v1.ApprovalRefR\bapproval\"a\n" +
	"\fOperationRef\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12'\n" +
	"\x0fmanifest_digest\x18\x03 \x01(\tR\x0emanifestDigest\"\xcb\x01\n" +
	"\x05Actor\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12#\n" +
	"\rdelegation_id\x18\x03 \x01(\tR\fdelegationId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05chain\x18\x05 \x03(\tR\x05chain\x12%\n" +
	"\x0etransaction_id\x18\x06 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\a \x01(\tR\tmessageId\"=\n" +
	"\aPEPInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\"\xb4\x01\n" +
	"\fRequestFacts\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\x12#\n" +
	"\rdelivery_mode\x18\x02 \x01(\tR\fdeliveryMode\x12\x1d\n" +
	"\n" +
	"terms_hash\x18\x03 \x01(\tR\ttermsHash\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05payee\x18\x06 \x01(\tR\x05payee\"\x9d\x01\n" +
	"\vApprovalRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\vapproved_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"approvedAt\x12A\n" +
	"\x0eapproved_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rapprovedUntil\"h\n" +
	"\x12EvaluationResponse\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\bR\bdecision\x126\n" +
	"\acontext\x18\x02 \x01(\v2\x1c.dx.authz.v1.DecisionContextR\acontext\"b\n" +
	"\x0fDecisionContext\x12\x1f\n" +
	"\vreason_user\x18\x01 \x01(\tR\n" +
	"reasonUser\x12.\n" +
	"\x02dx\x18\x02 \x01(\v2\x1e.dx.authz.v1.DXDecisionContextR\x02dx\"\xce\x02\n" +
	"\x11DXDecisionContext\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12#\n" +
	"\revaluation_id\x18\x02 \x01(\tR\fevaluationId\x12\x1f\n" +
	"\vreason_code\x18\x03 \x01(\tR\n" +
	"reasonCode\x12\x1a\n" +
	"\bcomplete\x18\x04 \x01(\bR\bcomplete\x12+\n" +
	"\x11evaluated_profile\x18\x05 \x01(\tR\x10evaluatedProfile\x12;\n" +
	"\vvalid_until\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\x121\n" +
	"\bevidence\x18\a \x01(\v2\x15.dx.authz.v1.EvidenceR\bevidence\x12 \n" +
	"\vattestation\x18\b \x01(\tR\vattestation\"\xf2\x01\n" +
	"\bEvidence\x12'\n" +
	"\x0fmanifest_digest\x18\x01 \x01(\tR\x0emanifestDigest\x12 \n" +
	"\ffga_model_id\x18\x02 \x01(\tR\n" +
	"fgaModelId\x12:\n" +
	"\x19grant_projection_revision\x18\x03 \x01(\tR\x17grantProjectionRevision\x128\n" +
	"\x18condition_schema_version\x18\x04 \x01(\x05R\x16conditionSchemaVersion\x12%\n" +
	"\x0emapping_digest\x18\x05 \x01(\tR\rmappingDigest\"V\n" +
	"\x12EvaluationsRequest\x12@\n" +
	"\vevaluations\x18\x01 \x03(\v2\x1e.dx.authz.v1.EvaluationRequestR\vevaluations\"X\n" +
	"\x13EvaluationsResponse\x12A\n" +
	"\vevaluations\x18\x01 \x03(\v2\x1f.dx.authz.v1.EvaluationResponseR\vevaluations2\xb7\x01\n" +
	"\x14AuthorizationService\x12K\n" +
	"\bEvaluate\x12\x1e.dx.authz.v1.EvaluationRequest\x1a\x1f.dx.authz.v1.EvaluationResponse\x12R\n" +
	"\rEvaluateBatch\x12\x1f.dx.authz.v1.EvaluationsRequest\x1a .dx.authz.v1.EvaluationsResponseB9Z7github.com/datakaveri/dx-common-go/grpc/authzpb;authzpbb\x06proto3"

var (
	file_dx_authz_v1_authz_proto_rawDescOnce sync.Once
	file_dx_authz_v1_authz_proto_rawDescData []byte
)

func file_dx_authz_v1_authz_proto_rawDescGZIP() []byte {
	file_dx_authz_v1_authz_proto_rawDescOnce.Do(func() {
		file_dx_authz_v1_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dx_authz_v1_authz_proto_rawDesc), len(file_dx_authz_v1_authz_proto_rawDesc)))
	})
	return file_dx_authz_v1_authz_proto_rawDescData
}

var file_dx_authz_v1_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_dx_authz_v1_authz_proto_goTypes = []any{
	(*EvaluationRequest)(nil),     // 0: dx.authz.v1.EvaluationRequest
	(*Subject)(nil),               // 1: dx.authz.v1.Subject
	(*Action)(nil),                // 2: dx.authz.v1.Action
	(*Resource)(nil),              // 3: dx.authz.v1.Resource
	(*RequestContext)(nil),        // 4: dx.authz.v1.RequestContext
	(*DXRequestContext)(nil),      // 5: dx.authz.v1.DXRequestContext
	(*OperationRef)(nil),          // 6: dx.authz.v1.OperationRef
	(*Actor)(nil),                 // 7: dx.authz.v1.Actor
	(*PEPInfo)(nil),               // 8: dx.authz.v1.PEPInfo
	(*RequestFacts)(nil),          // 9: dx.authz.v1.RequestFacts
	(*ApprovalRef)(nil),           // 10: dx.authz.v1.ApprovalRef
	(*EvaluationResponse)(nil),    // 11: dx.authz.v1.EvaluationResponse
	(*DecisionContext)(nil),       // 12: dx.authz.v1.DecisionContext
	(*DXDecisionContext)(nil),     // 13: dx.authz.v1.DXDecisionContext
	(*Evidence)(nil),              // 14: dx.authz.v1.Evidence
	(*EvaluationsRequest)(nil),    // 15: dx.authz.v1.EvaluationsRequest
	(*EvaluationsResponse)(nil),   // 16: dx.authz.v1.EvaluationsResponse
	(*structpb.Struct)(nil),       // 17: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_dx_authz_v1_authz_proto_depIdxs = []int32{
	1,  // 0: dx.authz.v1.EvaluationRequest.subject:type_name -> dx.authz.v1.Subject
	2,  // 1: dx.authz.v1.EvaluationRequest.action:type_name -> dx.authz.v1.Action
	3,  // 2: dx.authz.v1.EvaluationRequest.resource:type_name -> dx.authz.v1.Resource
	4,  // 3: dx.authz.v1.EvaluationRequest.context:type_name -> dx.authz.v1.RequestContext
	17, // 4: dx.authz.v1.Subject.properties:type_name -> google.protobuf.Struct
	17, // 5: dx.authz.v1.Action.properties:type_name -> google.protobuf.Struct
	17, // 6: dx.authz.v1.Resource.properties:type_name -> google.protobuf.Struct
	5,  // 7: dx.authz.v1.RequestContext.dx:type_name -> dx.authz.v1.DXRequestContext
	6,  // 8: dx.authz.v1.DXRequestContext.operation:type_name -> dx.authz.v1.OperationRef
	7,  // 9: dx.authz.v1.DXRequestContext.actor:type_name -> dx.authz.v1.Actor
	8,  // 10: dx.authz.v1.DXRequestContext.pep:type_name -> dx.authz.v1.PEPInfo
	9,  // 11: dx.authz.v1.DXRequestContext.request:type_name -> dx.authz.v1.RequestFacts
	10, // 12: dx.authz.v1.DXRequestContext.approval:type_name -> dx.authz.v1.ApprovalRef
	18, // 13: dx.authz.v1.ApprovalRef.approved_at:type_name -> google.protobuf.Timestamp
	18, // 14: dx.authz.v1.ApprovalRef.approved_until:type_name -> google.protobuf.Timestamp
	12, // 15: dx.authz.v1.EvaluationResponse.context:type_name -> dx.authz.v1.DecisionContext
	13, // 16: dx.authz.v1.DecisionContext.dx:type_name -> dx.authz.v1.DXDecisionContext
	18, // 17: dx.authz.v1.DXDecisionContext.valid_until:type_name -> google.protobuf.Timestamp
	14, // 18: dx.authz.v1.DXDecisionContext.evidence:type_name -> dx.authz.v1.Evidence
	0,  // 19: dx.authz.v1.EvaluationsRequest.evaluations:type_name -> dx.authz.v1.EvaluationRequest
	11, // 20: dx.authz.v1.EvaluationsResponse.evaluations:type_name -> dx.authz.v1.EvaluationResponse
	0,  // 21: dx.authz.v1.AuthorizationService.Evaluate:input_type -> dx.authz.v1.EvaluationRequest
	15, // 22: dx.authz.v1.AuthorizationService.EvaluateBatch:input_type -> dx.authz.v1.EvaluationsRequest
	11, // 23: dx.authz.v1.AuthorizationService.Evaluate:output_type -> dx.authz.v1.EvaluationResponse
	16, // 24: dx.authz.v1.AuthorizationService.EvaluateBatch:output_type -> dx.authz.v1.EvaluationsResponse
	23, // [23:25] is the sub-list for method output_type
	21, // [21:23] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_dx_authz_v1_authz_proto_init() }
func file_dx_authz_v1_authz_proto_init() {
	if File_dx_authz_v1_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dx_authz_v1_authz_proto_rawDesc), len(file_dx_authz_v1_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dx_authz_v1_authz_proto_goTypes,
		DependencyIndexes: file_dx_authz_v1_authz_proto_depIdxs,
		MessageInfos:      file_dx_authz_v1_authz_proto_msgTypes,
	}.Build()
	File_dx_authz_v1_authz_proto = out.File
	file_dx_authz_v1_authz_proto_goTypes = nil
	file_dx_authz_v1_authz_proto_depIdxs = nil
}
